### ISSUE TITLE
Feature: Adding a test suite

### ISSUE THREAD

**Issue by jmfrank63** [chrys-elrak/rock-paper-scissor#1]
Hi,

I found your project via the Hacktoberfest2022. I think it is a neat idea, and I would like to work on it a little. I will add a couple of feature request issues and add the appropriate PRs then. I hope this is ok. If you have any requests, let me know.

This feature request is for adding a simple test suite.

**Comment by chrys-elrak** [comment]
Thank you very much, obviously it would be necessary to provide tests, I hadn't thought of that. Luckily you did that.
